site_name: 2025 Python for Photonics
site_description: Documentation for 2025 IEEE Workshop Photonics Automation with Python
site_url: https://asrc-photonics.github.io/2025-python-for-photonics
repo_name: 2025-python-for-photonics

# Standard docs directory
docs_dir: docs

theme:
  name: material
  font: 
    text: Roboto
    code: Roboto Mono
  # icon:
  #   logo: octicons/globe/16
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    # - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.indexes
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - assets/css/schedule.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tasklist
  - pymdownx.details
  - admonition
  - toc:
      permalink: true
      # baselevel: 2
      # separator: "_"
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption



plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Program: 
    - Day 1 Symposium: program_day1.md
    - Day 1 Abstracts: abstracts.md
    - Days 2-4 Hands-on Sessions: program_days2-4.md
    - Days 2-4 Meet the Team: instructors.md
  - Registration: registration.md
  - Venue: venue.md
  - Days 2-4 Info: 
    - Prerequisites: prerequisites.md
    - Installation Guideline: python/guideline.md
    - Introduction to python: python/intro.md
    - Overview of classes: python/classes.md
    - Overview of devices: python/devices.md
    - Linear Stage: python/linear_stage.md
    - How to save and plot data: python/save_plot_data.md
    - Powermeter: python/powermeter.md
    - Knife-edge experiment: python/knife_edge.md
    - Team projects: projects.md
    - GUI Tutorial materials: gui.md
    - Data Processing Tutorial: kamyar.md
  - Contact: contact.md
  - Support the Workshop: support.md
  - Flyer: flyer.md

 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/asrc-photonics
    # - icon: fontawesome/brands/linkedin
    #   link: https://www.linkedin.com/in/worldlycode/


